//Records page Actions
export const DELETE_RECORD = "DELETE_RECORD";
export const OPEN_CSV_MODAL = "OPEN_CSV_MODAL";
export const UPLOAD_CSV = "UPLOAD_CSV";
export const CSV_PARSE_SUBMIT = "CSV_PARSE_SUBMIT";
export const CLOSE_CSV_MODAL = " CLOSE_CSV_MODAL";
export const OPEN_VIEW_USER_MODAL = "OPEN_VIEW_USER_MODAL";
export const CLOSE_VIEW_USER_MODAL = "CLOSE_VIEW_USER_MODAL";
export const OPEN_DELETE_DIALOGUE = "OPEN_DELETE_DIALOGUE";
export const CLOSE_DELETE_DIALOGUE = "CLOSE_DELETE_DIALOGUE";
export const SWITCH_USER = "SWITCH_USER";
export const ADD_USER_FORM_OPEN = "ADD_USER_FORM_OPEN";
export const ADD_USER_FORM_CLOSE = "ADD_USER_FORM_CLOSE";
export const ADD_USER_BETWEEN = "ADD_USER_BETWEEN";
export const ADD_USER_FORM_SUBMIT = "ADD_USER_FORM_SUBMIT";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
export const EDIT_USER_OPEN = "EDIT_USER_OPEN";
export const EDIT_USER_CLOSE = "EDIT_USER_CLOSE";
export const FILL_EDIT_FORM = "FILL_EDIT_FORM";
export const EDIT_LOCAL_LOADER = "EDIT_LOCAL_LOADER";
export const EDIT_USER_FORM_SUBMIT = "EDIT_USER_FORM_SUBMIT";
export const DATA_FETCHED = "DATA_FETCHED";
export const CLOSE_MSG_MODAL = "CLOSE_MSG_MODAL";
export const DELETE_OPEN_LOCAL_LOADER = "DELETE_OPEN_LOCAL_LOADER";
export const FORM_LOCAL_LOADER_OPEN = "FORM_LOCAL_LOADER_OPEN";
export const LOGIN_DATA_FETCHED = "LOGIN_DATA_FETCHED";
export const LOGIN_CLICKED = "LOGIN_CLICKED";
export const REFER_EMAIL = "REFER_EMAIL";
export const EMPLOYER_FORM_SUBMIT = "EMPLOYER_FORM_SUBMIT";
export const EMPLOYER_CLICKED = "EMPLOYER_CLICKED";
export const SWITCH_CLICKED = "SWITCH_CLICKED";
export const STATUS_CHANGED = "STATUS_CHANGED";
export const SWITCH_ERROR = "SWITCH_ERROR";
export const CSV_ERROR = "CSV_ERROR";
export const CSV_CLICKED = "CSV_CLICKED";
export const SEARCH_TABLE_CHANGE = "SEARCH_TABLE_CHANGE";
export const ISSUE_CLICKED = "ISSUE_CLICKED";
export const ISSUE_CLOSE = "ISSUE_CLOSE";
export const PAGE_LOAD_START = "PAGE_LOAD_START";
export const RESEND_MAIL = "RESEND_MAIL";
export const RESEND_SUCCESS = "RESEND_SUCCESS";
export const RESEND_FAIL = "RESEND_FAIL";
export const OVERDUE_ID_SET = "OVERDUE_ID_SET";
export const OVERDUE_ID_REMOVE = "OVERDUE_ID_REMOVE";
export const ISSUES_ID_SET = "ISSUES_ID_SET";
export const ISSUES_ID_REMOVE = "ISSUES_ID_REMOVE";
export const TODO_ID_SET = "TODO_ID_SET";
export const TODO_ID_REMOVE = "TODO_ID_REMOVE";
export const ISSUE_STATUS_UPDATE = "ISSUE_STATUS_UPDATE";
export const ALERTS_EDITED = "ALERTS_EDITED";
export const PAY_OVERDUE = "PAY_OVERDUE";
export const ISSUES_DATA_FETCHED = "ISSUES_DATA_FETCHED";
export const TODO_STATUS_UPDATE = "TODO_STATUS_UPDATE";
export const TODOS_DATA_FETCHED = "TODOS_DATA_FETCHED";
export const EMPLOYEES_DATA_FETCHED = "EMPLOYEES_DATA_FETCHED";
export const CREDIT_GIVEN_GRAPH_UPDATE = "CREDIT_GIVEN_GRAPH_UPDATE";
export const USAGE_GRAPH_UPDATE = "USAGE_GRAPH_UPDATE";
export const OPEN_PAYDAY_CHANGE_DIALOGUE = "OPEN_PAYDAY_CHANGE_DIALOGUE";
export const CLOSE_PAYDAY_CHANGE_DIALOGUE = "CLOSE_PAYDAY_CHANGE_DIALOGUE";
export const UPDATE_PAYDAY_VALUE = "UPDATE_PAYDAY_VALUE";
export const TEMP_UPDATE_PAYDAY_VALUE = "TEMP_UPDATE_PAYDAY_VALUE";
export const PAYDAY_OPEN_LOCAL_LOADER = "PAYDAY_OPEN_LOCAL_LOADER";
export const TODOS_PAGES_DATA_FETCHED = "TODOS_PAGES_DATA_FETCHED";
export const DEFAULTER_LIST_DATA_FETCHED = "DEFAULTER_LIST_DATA_FETCHED";
export const PROFILE_DATA_FETCHED = "PROFILE_DATA_FETCHED";
export const PASSWORD_MAIL_SENT = "PASSWORD_MAIL_SENT";
export const EDIT_USER_SALARY_OPEN = "EDIT_USER_SALARY_OPEN";
export const EDIT_USER_SALARY_CLOSE = "EDIT_USER_SALARY_CLOSE";

//Dashboard Actions
export const OPEN_ADD_TODO_MODAL = "OPEN_ADD_TODO_MODAL";
export const CLOSE_ADD_TODO_MODAL = "CLOSE_ADD_TODO_MODAL";
export const SUBMIT_TODO = "SUBMIT_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const OPEN_PROFILE_DROP = "OPEN_PROFILE_DROP";
export const CLOSE_PROFILE_DROP = "CLOSE_PROFILE_DROP";
export const OPEN_WHATS_NEW = "OPEN_WHATS_NEW";
export const CLOSE_WHATS_NEW = "CLOSE_WHATS_NEW";
export const OPEN_DROP_NOTIF = "OPEN_DROP_NOTIF";
export const CLOSE_DROP_NOTIF = "CLOSE_DROP_NOTIF";
export const DEFAULTER_MODAL_OPEN = "DEFAULTER_MODAL_OPEN";
export const DEFAULTER_MODAL_CLOSE = "DEFAULTER_MODAL_CLOSE";
export const EACH_TODO_CLICKED = "EACH_TODO_CLICKED";
export const TODO_DESC_CLOSE = "TODO_DESC_CLOSE";
export const DATA_FETCH_REMAINING = "DATA_FETCH_REMAINING";
export const OPEN_EDIT_TODO = "OPEN_EDIT_TODO";
export const CLOSE_EDIT_TODO = "CLOSE_EDIT_TODO";
export const TODO_EDITED = "TODO_EDITED";
export const SEARCH_TABLE_CHANGE_EMP=  "SEARCH_TABLE_CHANGE_EMP";


//Side DrawerActions
export const ACTIVE_STATE_SIDEBAR = "ACTIVE_STATE_SIDEBAR";

//Login Page Actions
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const LOGIN_ERROR = "LOGIN_ERROR";

//salers reducer
export const EMPLOYER_SALES = "EMPLOYER_SALES";
export const EMPLOYEE_SALES = "EMPLOYEE_SALES";
export const CALC_SWITCHED = "CALC_SWITCHED";
export const EXIT_CALC = "EXIT_CALC";
